USE [master]
GO
/****** Object:  Database [ErrorSimDB]    Script Date: 25-Mar-26 18:12:26 ******/
CREATE DATABASE [ErrorSimDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ErrorSimDB', FILENAME = N'C:\Users\AllbinKGeorge\ErrorSimDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ErrorSimDB_log', FILENAME = N'C:\Users\AllbinKGeorge\ErrorSimDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [ErrorSimDB] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ErrorSimDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ErrorSimDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ErrorSimDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ErrorSimDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ErrorSimDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ErrorSimDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [ErrorSimDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [ErrorSimDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ErrorSimDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ErrorSimDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ErrorSimDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ErrorSimDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ErrorSimDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ErrorSimDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ErrorSimDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ErrorSimDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ErrorSimDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ErrorSimDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ErrorSimDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ErrorSimDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ErrorSimDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ErrorSimDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ErrorSimDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ErrorSimDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ErrorSimDB] SET  MULTI_USER 
GO
ALTER DATABASE [ErrorSimDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ErrorSimDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ErrorSimDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ErrorSimDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ErrorSimDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ErrorSimDB] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [ErrorSimDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [ErrorSimDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [ErrorSimDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [ErrorSimDB]
GO
/****** Object:  Table [dbo].[SimulationLogs]    Script Date: 25-Mar-26 18:12:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SimulationLogs](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Type] [nvarchar](50) NULL,
	[Message] [nvarchar](max) NULL,
	[CreatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[SimulationLogs] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
USE [master]
GO
ALTER DATABASE [ErrorSimDB] SET  READ_WRITE 
GO
